//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogNew.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int Id { get; set; }
        public string MakaleAdi { get; set; }
        public string MakaleOzeti { get; set; }
        public string MakaleDetayi { get; set; }
        public string Resim { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
