//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogNew.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string Yorum1 { get; set; }
        public Nullable<int> MakaleId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
